
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mldchan
      - MONGO_INITDB_ROOT_PASSWORD=changemeinprod

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mldchan
      - ME_CONFIG_MONGODB_ADMINPASSWORD=changemeinprod
      - ME_CONFIG_MONGODB_URL=mongodb://mldchan:changemeinprod@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false

  girlsocial-server:
    build:
      context: .
      target: dev
    ports:
      - "8082:3000"
    develop:
      watch:
        - path: src
          action: sync
          target: /app/src
        - path: public
          action: sync
          target: /app/public
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
